[firebase]
type = "service_account"
project_id = "credit-card-fraud-detect-775f4"
private_key_id = "e65ebd74c2899c4a828c7f2233d898b01ca74c3d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEKl/w4aGanmhC
+BFqokXKMINOENjNAGi5LlX9hNSJOxtPlc3KByf44XVk/0TccTTHZZsdklfgwXXr
73aWWVohOR5ZcoDv95sigkFeCbsBayl15/xkKa6536X94Z2toFATxzEk1yfbiCDd
T6H5bPd47BVmdU4f97MqZjjVBNPyb3Dc8UYI7pZ66rvrk0XUYGCXCsjPKIl8KZAM
AUjY1t1vrSkbJws0UQEIWBGLcZyuMfFvDCR9sbwJAqYmTDhm+1LEixsudk1ZQo+I
+JIV0ds8u/yKgv+RFuhoNNmAgBGrpmt6xQj5bXOBpRZ7UFufl6e4/2A/Lf8aIhT8
33C61REVAgMBAAECgf9iY0Tuv2+BtyT6cdfkCkyQT8S+/IDz6to1OjuAheutTysw
WSWq+4V3TtDF10KygUhd7WUSoyCjmf5X8Vy8cnrCLxcJxf4YxBfYA+MrrbW3ZtT+
Til8E2v1zjamUukpX6UwrLeS9fChXnJQjgaveffYrpBzn/v1pkcDY3UdyOe4SbJT
KhgWgHalHHzJOL1KP1Rxu5Cy2HL7pq+Cidtx1xyC1Y+xQ4WNDaDIPtHicbsNneJh
PpcFwo3hTCb/FIE7w0WZP0F/97oI1pcdFKrwm9APiZaaFGcG3M24Vv451Uj35GQr
9bbb+UeccORZpUUIpINMO58IspL6oebI7HEpukECgYEA4HI85ec8DGjgGVSci0aM
hAAjUU+I7P+CeSWqc1T/JWVyx4Amj7g/LRNxf4K/6u6pAwhPhIUavNFKyT1Wfa2/
V5/loijpbD1AwsxG9vL57717zcphqc0TB+ICSvE+1w/J6300vg30kqIUpnJqGIQY
w0UDeaDRoH1NcdKXGtlbdlkCgYEA375SPogvckBY7PZyfbiFRHtD9XE/N4ua/XUL
iPzeldgX8bOst0SxXw0UBjYGMyYelq6njRiXCxm1Z+NQC3G4+tJEEXOPOAiJubFj
FrVuvky1UZAk6knd71AUbLvc66cSaYhtbfjasdm9sKaIHd13BhEzfTbYw75QFysH
rwdq0R0CgYEAnJQVl+2xHpcrf4BflWoqLQxLlzX9OBkoVIvKVZs+REB5ymPEgw7u
Q+wEiggVCzhkABGUJ8cT2BXKLon0BMlpax/Je08/SJuSylLoTu9DHdT6wZ4mc+b1
F9K79rxGMpJ5Myet28iwjns0HMpE6cV94PwMaJWgqG3B0V4wvDJWdEECgYEAtrNH
n04/SBEpTB4V8XkaQYhSPvrBf07dObg4uhyaeUtiifiIwYIzQAWC42t79opbEfn+
UWXR+Lt+eR2SADZVsWK/OGzfdwbpx5sE6ccvbe9fZAHLUxEMS91dQEjLJhZgH5LK
oLFDi1Tc44GoxpJQHcEwBUAjEvu1lKWLea4Z2DUCgYEAtM7ntkd+xMnkKVQE2G3o
j1I9g5IBG/T6EUEUCVwpw2lvxS0STfVGUtdcuyqCTjjdO/CvSXcfg1iGbN9mr+t1
Y7X4Sb5MzDF+DOnIfzMdQzdzI6t5NEWnjLNv6qpqOM1ZeQhLaLmOR+uG7ZfJ9idK
I0P36tsPZjl0PdDjXAzaFlQ=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@credit-card-fraud-detect-775f4.iam.gserviceaccount.com"
client_id = "112186106514477027490"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40credit-card-fraud-detect-775f4.iam.gserviceaccount.com"
